#!/bin/bash
# Decrypts the repository.
set -e # Exit with nonzero exit code if anything fails

cd "$(dirname "$0")/.."
# Pull requests and commits to other branches cannot decrypt data.
if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    echo "Skipping decryption"
    exit 0
fi
./scripts/get_keys
./gpg/decrypt.sh ./cyto_encryption_pass
