#!/bin/bash
# Commits all changed files and pushes to GitHub target branch.
set -e # Exit with nonzero exit code if anything fails

cd "$(dirname "$0")/.."

# Remote url
REPO=`git config remote.origin.url`

# Clone the existing gh-pages for this repo into out/
# Create a new empty branch if gh-pages doesn't exist yet (should only happen on first deply).
git clone $REPO out
cd out
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
cd ..
