#!/bin/bash
# Decrypt pgp key and add github deploy key to keyring
set -e # Exit with nonzero exit code if anything fails

# Get the deploy key by using Travis's stored variables to decrypt deploy_key.enc
chmod 600 ./cyto-github-deploy
eval `ssh-agent -s`
ssh-add cyto-github-deploy

# Import the pgp key into gpg
gpg --import < ./cyto_encryption.asc
