#!/bin/bash
# Decrypt pgp key and add github deploy key to keyring
set -e # Exit with nonzero exit code if anything fails

# Extract the secrets from the archive
tar -xvf secrets.tar

# Import the deploy key
chmod 600 ./cyto-github-deploy
eval `ssh-agent -s`
ssh-add cyto-github-deploy

# Import the pgp key into gpg
chmod 600 ./cyto_encryption.asc
gpg --import < ./cyto_encryption.asc
